name: autoruff

on:
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint with Ruff
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      - name: Run Ruff linting
        run: ruff check . --output-format=full

      - name: Run Ruff formatting check
        run: ruff format --check .
