name: Update Court Data

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write  # Grant write permission to GITHUB_TOKEN

jobs:
  update-court-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.5"
          enable-cache: true
          cache-dependency-glob: "requirements**.txt"

      - name: Set up Python 3.12
        run: uv python install '3.12'

      - name: Install the project
        run: uv sync

      - name: Run Update Script
        run: |
          uv run main.py

      - name: Set Date Environment Variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            chore(court_data): update court data on $(date +'%Y-%m-%d')
          file_pattern: court_data/**/*
          branch: main  # Replace with your target branch
          commit_options: '--no-verify'  # Optional: skip pre-commit hooks